server:
  port: 9002



producto:
  service:
    url: http://localhost:9007/productos  
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dbropa
    username: root
    password: mysql
  jpa:
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

